name = Adventurelands
title = Adventurelands
author = TechnoWolfTV
description = A Minetest game featuting exploration, mining, crafting, building and survival with monsters and animals. Adventurelands includes carefully selected mods for an optimal balance between form and function.
version= 1.0.15
