name = Adventurelands
title = Adventurelands
author = TechnoWolfTV
description = A Luanti (formerly Minetest) game featuring exploration, mining, crafting, building and survival with monsters and animals. Adventurelands includes carefully selected mods for an optimal balance between form and function.
min_minetest_version = 5.12.0
version= 1.0.78
