name = Adventurelands
title = Adventurelands
author = TechnoWolfTV
description = An exploration, mining, crafting, building and survival sandbox game with monsters and animals. Adventurelands game includes carefully selected mods for an optimal balance between form and function.
version= 1.0.2
